
# -----------------------------------------------------
# Key bindings
# name: "Scrolling"
# -----------------------------------------------------

# SUPER KEY
$mainMod = SUPER
$HYPRSCRIPTS = ~/.config/hypr/scripts
$SCRIPTS = ~/.config/ml4w/scripts

# bind = $mainMod, O, overview:toggle                                   # 
bind = $mainMod, P, exec, grim -g "$(slurp -o -c '##20ff0fA0')" -t ppm - | satty --filename -

# bind = $mainMod, W, global, caelestia:launcher
# biactiveainMod, Space, exec, ~/.config/eww/bin/sirula                # Open launcher

# bind = ALT, TAB, exec, ~/.config/eww/scripts/toggleTask.sh 

# Display
bind = $mainMod SHIFT, mouse_down, exec, hyprctl keyword cursor:zoom_factor $(awk "BEGIN {print $(hyprctl getoption cursor:zoom_factor | grep 'float:' | awk '{print $2}') + 0.5}") # Increase display zoom
bind = $mainMod SHIFT, mouse_up, exec, hyprctl keyword cursor:zoom_factor $(awk "BEGIN {print $(hyprctl getoption cursor:zoom_factor | grep 'float:' | awk '{print $2}') - 0.5}") # Decrease display zoom
bind = $mainMod SHIFT, Z, exec, hyprctl keyword cursor:zoom_factor 1 # Reset display zoom


bind = $mainMod SHIFT, G, lockGroups, toggle
bind = $mainMod SHIFT, N, changegroupactive, b
# bind = $mainMod, K, swapsplit # Swapsplit

# Actions
bind = $mainMod CTRL, Q, exec, ~/.config/ml4w/scripts/wlogout.sh                          # Start wlogout
bind = $mainMod SHIFT, S, exec, $HYPRSCRIPTS/hyprshade.sh                                 # Toggle screenshader

# bind = $mainMod SHIFT, H, exec, $HYPRSCRIPTS/hyprshade.sh                               # Start wlogout
# bind = CTRL, Tab, exec, ~/.config/ml4w/scripts/focus.sh                                 # Open Select Window Menu
# bind = $mainMod, N, exec, caelestia shell drawers toggle sidebar      # notification


bind = $mainMod CTRL, 1, exec, $HYPRSCRIPTS/moveTo.sh 1  # Move all windows to workspace 1
bind = $mainMod CTRL, 2, exec, $HYPRSCRIPTS/moveTo.sh 2  # Move all windows to workspace 2
bind = $mainMod CTRL, 3, exec, $HYPRSCRIPTS/moveTo.sh 3  # Move all windows to workspace 3
bind = $mainMod CTRL, 4, exec, $HYPRSCRIPTS/moveTo.sh 4  # Move all windows to workspace 4
bind = $mainMod CTRL, 5, exec, $HYPRSCRIPTS/moveTo.sh 5  # Move all windows to workspace 5
bind = $mainMod CTRL, 6, exec, $HYPRSCRIPTS/moveTo.sh 6  # Move all windows to workspace 6
bind = $mainMod CTRL, 7, exec, $HYPRSCRIPTS/moveTo.sh 7  # Move all windows to workspace 7
bind = $mainMod CTRL, 8, exec, $HYPRSCRIPTS/moveTo.sh 8  # Move all windows to workspace 8
bind = $mainMod CTRL, 9, exec, $HYPRSCRIPTS/moveTo.sh 9  # Move all windows to workspace 9
bind = $mainMod CTRL, 0, exec, $HYPRSCRIPTS/moveTo.sh 10 # Move all windows to workspace 10

bind = $mainMod CTRL, down, workspace, empty # Open the next empty workspace


# Fn keys
bind = , XF86Calculator, exec, ~/.config/ml4w/settings/calculator.sh                                                                                         # Open calculator
bind = , XF86Lock, exec, hyprlock                                                                                                                            # Open screenlock

bind = , code:238, exec, brightnessctl -d smc::kbd_backlight s +10
bind = , code:237, exec, brightnessctl -d smc::kbd_backlight s 10-

