# -----------------------------------------------------
# Layouts
# -----------------------------------------------------

dwindle {
    preserve_split = true
}

master {
    # Commented out due to compatibility reasons
    # new_status = master
}

scrolling {
  fullscreen_on_one_column = true
  column_width= 0.8
  focus_fit_method = 0
}

gesture = 3, horizontal, workspace

binds {
  workspace_back_and_forth = false
  allow_workspace_cycles = true
  pass_mouse_when_bound = false
}
