
$background = rgba(12131890)

$error = rgba(ffb4ab90)

$error_container = rgba(93000a90)

$inverse_on_surface = rgba(2f303690)

$inverse_primary = rgba(485d9290)

$inverse_surface = rgba(e2e2e990)

$on_background = rgba(e2e2e990)

$on_error = rgba(69000590)

$on_error_container = rgba(ffdad690)

$on_primary = rgba(172e6090)

$on_primary_container = rgba(dae2ff90)

$on_primary_fixed = rgba(00184790)

$on_primary_fixed_variant = rgba(30457890)

$on_secondary = rgba(2a304290)

$on_secondary_container = rgba(dce2f990)

$on_secondary_fixed = rgba(151b2c90)

$on_secondary_fixed_variant = rgba(40465990)

$on_surface = rgba(e2e2e990)

$on_surface_variant = rgba(c5c6d090)

$on_tertiary = rgba(41274290)

$on_tertiary_container = rgba(fed7f990)

$on_tertiary_fixed = rgba(2a122c90)

$on_tertiary_fixed_variant = rgba(593d5990)

$outline = rgba(8f909990)

$outline_variant = rgba(44464f90)

$primary = rgba(b1c5ff90)

$primary_container = rgba(30457890)

$primary_fixed = rgba(dae2ff90)

$primary_fixed_dim = rgba(b1c5ff90)

$scrim = rgba(00000090)

$secondary = rgba(c0c6dd90)

$secondary_container = rgba(40465990)

$secondary_fixed = rgba(dce2f990)

$secondary_fixed_dim = rgba(c0c6dd90)

$shadow = rgba(00000090)

$source_color = rgba(447cf490)

$surface = rgba(12131890)

$surface_bright = rgba(38393f90)

$surface_container = rgba(1e1f2590)

$surface_container_high = rgba(282a2f90)

$surface_container_highest = rgba(33343a90)

$surface_container_low = rgba(1a1b2190)

$surface_container_lowest = rgba(0d0e1390)

$surface_dim = rgba(12131890)

$surface_tint = rgba(b1c5ff90)

$surface_variant = rgba(44464f90)

$tertiary = rgba(e0bbdd90)

$tertiary_container = rgba(593d5990)

$tertiary_fixed = rgba(fed7f990)

$tertiary_fixed_dim = rgba(e0bbdd90)

